name: Python Script CI/CD

on:
  push:
    branches:
      - main  

jobs:
  run-script:
    name: Run Python Script
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you need
          
      - name: Set up node.js   
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run script
        run: C:\Program Files\Git\PythonTest\python_selenium_tests\python UI_test.py
